-- create database
CREATE DATABASE Ruby-Capstone

-- use database
USE Ruby-Capstone

-- table item
CREATE TABLE Item (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_id INT,
    author_id INT,
    source_id INT,
    label_id INT,
    publish_date DATE,
    archived BOOLEAN,
    FOREIGN KEY (genre_id) REFERENCES Genre(id),
    FOREIGN KEY (author_id) REFERENCES Author(id),
    FOREIGN KEY (source_id) REFERENCES Source(id),
    FOREIGN KEY (label_id) REFERENCES Label(id)
);

-- genre table
CREATE TABLE Genre (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200)
);

-- music_album table
CREATE TABLE MusicAlbum (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200),
    on_spotify BOOLEAN,
    FOREIGN KEY(item_id) REFERENCES Item(id)
);